dask:
  partitions: -1 # if 0, 1 row per surface otherwise number of partitions


memory_cache_location: '/home/jovyan/shared-scratch/Inference/debug_cache'

output_options:
  pickle_path: '/home/jovyan/Pt_H_example.pkl'
  verbose: False
  config_path: '/home/jovyan/Pt_H_example.yml'

adsorbate_filters:
  filter_by_smiles: ['*H']

slab_filters:
  filter_by_object_size: 80
  filter_by_max_miller_index: 2

adslab_prediction_steps:
- step: predict
  type: direct
  gpu: false
  batch_size: 4
  label: 'dE_gemnet_is2re_finetuned'
  checkpoint_path: 'configs/ocp_config_checkpoints/gemnet-is2re-finetuned-11-01.pt'
  
bulk_filters:
  filter_by_object_size: 60 # 60
  filter_by_mpids:
  - 'mp-126'