dask:
  config: |
    from dask.distributed import Client
    from dask_kubernetes import KubeCluster
    import dask
    import os
    from jinja2 import Template

    dask.config.set({"distributed.comm.timeouts.connect":120})
    dask.config.set({"distributed.scheduler.allowed_failures":20})
    dask.config.set({"distributed.comm.retry.count":20})

    cluster = KubeCluster(pod_template = 'configs/debug_configs/workers-cpu-dev.yml',
                          namespace='zulissi',
                          name='dask-catlas-dev',
                          scheduler_service_wait_timeout = 120)
    cluster.adapt(minimum=8, maximum=100, interval="30000 ms")
    client = Client(cluster)

  partitions: -1 # if 0, 1 row per surface otherwise number of partitions


memory_cache_location: '/home/jovyan/shared-scratch/catlas_cache_v2'

output_options:
  pickle: True # True pickles the resulting predictions
  pickle_path: '/home/jovyan/shared-scratch/zulissi/co2rr_nitrides_miller2.pkl'
  optional_additional_path_str: 'CO2RR_test_screen'
  verbose: False

bulk_filters:
  filter_by_acceptable_elements: ['N', 'Sc', 'Ti', 'V', 'Cr', 'Mn', 'Fe', 'Co', 'Ni', 'Cu', 'Zn', 'Y', 'Zr', 'Nb', 'Mo', 'Tc', 'Ru', 'Rh', 'Pd', 'Ag', 'Cd', 'Ta', 'W', 'Re', 'Os', 'Ir', 'Pt', 'Au', 'Hg', 'Al', 'Ga', 'Sn', Pb', 'Bi', 'In']
  filter_by_object_size: 40 # 60
  filter_by_required_elements: ['N']

adsorbate_filters:
  filter_by_smiles: ['*H', '*CO','*OH','*CHO']

slab_filters:
  filter_by_object_size: 80
  filter_by_max_miller_index: 2

adslab_prediction_steps:
- step: predict
  type: direct
  gpu: false
  batch_size: 4
  label: 'dE_gemnet_is2re_finetuned'
  checkpoint_path: '/home/jovyan/catlas/configs/ocp_config_checkpoints/gemnet-is2re-finetuned-11-01.pt'
