dask:
  partitions: -1 # if -1, 1 row per surface otherwise number of partitions

memory_cache_location: '/home/jovyan/shared-scratch/Brook/cacheatache'

input_options:
    bulk_file: 'catlas/bulk_structures/ocdata_bulks.db'

output_options:
  pickle_path: 'pourbaix_check.pkl'
  config_path: 'pourbaix_check.yml'
  verbose: False

bulk_filters:
    filter_by_element_groups: ["transition metal"]
    filter_by_num_elements: [2]
    filter_by_pourbaix_stability:
      conditions: 
        - pH: 6
          V: 2 
      max_decomposition_energy: 0.05


adsorbate_filters:
    filter_by_smiles: ['*H']

slab_filters:
    filter_by_object_size: 200
    filter_by_max_miller_index: 2
    
adslab_prediction_steps:
  - step: predict
    gpu: false
    batch_size: 4
    label: 'dE_gemnet_is2re_finetuned'
    checkpoint_path: 'ocp_checkpoints/gemnet-is2re-finetuned-11-01.pt'