kind: Pod
spec:
  restartPolicy: Never
  containers:
  - image: ulissigroup/kubeflow:predictions
    imagePullPolicy: Always
    args: [dask-worker, --nthreads, '1',--nprocs,'2', --no-dashboard, --memory-limit,'8 GiB',--death-timeout, '600']
    name: dask
    env:
    - name: OMP_NUM_THREADS
      value: 4
    - name: PYTHONPATH
      value: "/home/jovyan/ocp:/home/jovyan/catlas"
    - name: NVIDIA_VISIBLE_DEVICES
      value: "none"
    - name: MALLOC_TRIM_THRESHOLD_
      value: 0
    resources:
      limits:
        cpu: "4"
        memory: 17G
        nvidia.com/gpu: "0"
      requests:
        cpu: "4"
        memory: 17G
        nvidia.com/gpu: "0"
    volumeMounts:
    - mountPath: /home/jovyan/ocp
      name: workspace-inference
      subPath: ocp
    - mountPath: /home/jovyan/catlas
      name: workspace-inference
      subPath: catlas
    - mountPath: /home/jovyan/shared-scratch
      name: shared-scratch
    - mountPath: /home/jovyan/dask-worker-space
      name: shared-scratch
      subPath: catlas/dask-worker-space
  volumes:
  - name: workspace-inference
    persistentVolumeClaim:
      claimName: workspace-inference
  - name: shared-scratch
    persistentVolumeClaim:
      claimName: shared-scratch
      
