dask_config: |
  from dask.distributed import Client, LocalCluster
  cluster = LocalCluster(n_workers=4, threads_per_worker=1)
  client = Client(cluster)

memory_cache_location: '/home/jovyan/shared-scratch/inference_cache'

output_options:
  pickle_path: None # '/home/jovyan/shared-scratch/Inference/test_screen.pkl'
  verbose: False

# optional filters
bulk_filters:
    filter_by_mpids: None # ['mp-126']

    filter_by_acceptable_elements: ['Pt'] # element_list: ['Cu', 'Pt', 'Sn', 'Al', 'Au'] #, 'Pd', 'Zn', 'Rh', 'Ru', 'Ir', 'Cr', 'In', 'Ga', 'Bi', 'Po', 'Tl', 'W', 'Y', 'Fe']

    filter_by_num_elements: [1] # [1,2]

    filter_by_object_size: 60 # 60

    filter_by_Pourbaix_stability: 
      pH: [3,3]
      pH_step: 0.5 # step size between pH points considered
      applied_potential: [-1.3, -0.6]
      applied_potential_step: 0.05 # step size between applied potential points considered
      max_decomposition_E: 0.1 # eV/(metal atom)
      
adsorbate_filters:
    filter_by_smiles: ['*H']

slab_filters:
    filter_by_object_size: 100
    
    filter_by_max_miller_index: 1
    
adslab_prediction_steps:
  - step: predict
    type: direct
    label: 'dE_gemnet_is2re_finetuned'
    config_path: 'configs/ocp_config_checkpoints/s2ef_all_gemnet-dT.yml'
    checkpoint_path: 'configs/ocp_config_checkpoints/gemnet_is2re_finetuned.pt'
  #- step: predict
  #  type: relaxation
  #  config_path: 'configs/ocp_config_checkpoints/s2ef_all_gemnet-dT.yml'
  #  checkpoint_path: 'configs/ocp_config_checkpoints/gemnet_t_direct_h512_all.pt'
