dask_config: |
  from dask.distributed import Client
  client = Client()

memory_cache_location: '/home/jovyan/shared-scratch/inference_cache'

output_options:
  pickle: False # True pickles the resulting predictions
  optional_additional_path_str: 'HER_test_screen'

# optional filters
bulk_filters:
    filter_by_mpids: ['mp-126']

    filter_by_elements: None # element_list: ['Cu', 'Pt', 'Sn', 'Al', 'Au'] #, 'Pd', 'Zn', 'Rh', 'Ru', 'Ir', 'Cr', 'In', 'Ga', 'Bi', 'Po', 'Tl', 'W', 'Y', 'Fe']

    filter_by_number_elements: None # [1,2]

    filter_by_object_size: None # 60

    filter_by_Pourbaix_stability: 
      pH: [3,3]
      pH_step: 0.5 # step size between pH points considered
      applied_potential: [-1.3, -0.6]
      applied_potential_step: 0.05 # step size between applied potential points considered
      max_decomposition_E: 0.1 # eV/(metal atom)
      
adsorbate_filters:
    filter_by_smiles: ['*H']

slab_filters:
    filter_by_object_size: 100
    
adslab_prediction_steps:
  - step: predict
    type: direct
    config_path: 'configs/s2ef/2M/gemnet/gemnet-dT.yml'
    checkpoint_path: '/home/jovyan/software/dask-predictions/configs/ocp_config_checkpoints/gemnet_is2re_finetuned.pt'
  - step: predict
    type: relaxation
    config_path: 'configs/s2ef/2M/gemnet/gemnet-dT.yml'
    checkpoint_path: '/home/jovyan/software/dask-predictions/configs/ocp_config_checkpoints/gemnet_t_direct_h512_all.pt'
