
# general

direct_prediction_mode: True # False -> relaxation approach
adsorbate_smile_list: ['*CH2']

dask_config: |
  from dask.distributed import Client
  client = Client()

output_options:
  pickle: False # True pickles the resulting predictions
  optional_additional_path_str: 'my_experiment'

# optional filters
filter_by_mpids: 
  enable: True
  mpid_list: ['mp-10004']

filter_by_elements:
  enable: False
  element_list: ['Cu', 'Pt', 'Sn', 'Al', 'Au'] #, 'Pd', 'Zn', 'Rh', 'Ru', 'Ir', 'Cr', 'In', 'Ga', 'Bi', 'Po', 'Tl', 'W', 'Y', 'Fe']

filter_by_number_elements: 
  enable: False
  number_of_els: [1,2]
  
filter_by_object_size:
  enable: False
  max_size: 60
  
filter_by_Pourbaix_stability:
  enable: True
  pH: [3,3]
  pH_step: 0.5 # step size between pH points considered
  applied_potential: [-1.3, -0.6]
  applied_potential_step: 0.05 # step size between applied potential points considered
  max_decomposition_E: 0.1 #unit? eV/fu?


# paths
config_path: '/home/jovyan/ocp/configs/is2re/all/dimenet_plus_plus/dpp.yml'
checkpoint_path : '/home/jovyan/ocp/data/OC20/pretrained/is2re/dimenetpp_all.pt'
shared_scratch_path: '/home/jovyan/shared-scratch/Brook'
worker_spec_path: '/home/jovyan/ocp/dask-predictions/worker-spec.yml'

