kind: Pod
metadata:
  namespace: dask
spec:
  restartPolicy: Never
  containers:
  - image: ulissigroup/kubeflow:predictions
    imagePullPolicy: Always
    args: [dask-worker, --nthreads, '1',--nprocs,'1', --no-dashboard, --memory-limit,'15 GiB',--death-timeout, '600']
    name: dask
    env:
    - name: OMP_NUM_THREADS
      value: 1
    - name: PYTHONPATH
      value: "/home/jovyan/ocp:/home/jovyan/catlas"
    resources:
      limits:
        cpu: "1"
        memory: 15G
      requests:
        cpu: "1"
        memory: 15G
    volumeMounts:
    - mountPath: /home/jovyan/ocp
      name: workspace-inference
      subPath: ocp
    - mountPath: /home/jovyan/catlas
      name: workspace-inference
      subPath: catlas
    - mountPath: /home/jovyan/shared-data
      name: shared-datasets
    - mountPath: /home/jovyan/shared-scratch
      name: scratch-scratch
  volumes:
  - name: workspace-inference
    persistentVolumeClaim:
      claimName: workspace-inference
  - name: shared-datasets
    persistentVolumeClaim:
      claimName: shared-datasets
  - name: scratch-scratch
    persistentVolumeClaim:
      claimName: shared-scratch
      
      
      
