
trainer: energy

dataset:
  - src: /home/jovyan/catlas/configs/ocp_config_checkpoints/data.lmdb
    normalize_labels: True
    target_mean: -1.525913953781128
    target_std: 2.279365062713623

task:
  dataset: single_point_lmdb
  description: "Relaxed state energy prediction from initial structure."
  type: regression
  metric: mae
  labels:
    - relaxed energy

logger: wandb

model:
  name: gemnet_t
  activation: silu
  cbf:
    name: spherical_harmonics
  cutoff: 6.0
  direct_forces: true
  emb_size_atom: 512
  emb_size_bil_trip: 64
  emb_size_cbf: 16
  emb_size_edge: 512
  emb_size_rbf: 16
  emb_size_trip: 64
  envelope:
    exponent: 5
    name: polynomial
  extensive: true
  num_after_skip: 2
  num_atom: 3
  num_before_skip: 1
  num_blocks: 3
  num_concat: 1
  num_radial: 128
  num_spherical: 7
  otf_graph: false
  output_init: HeOrthogonal
  rbf:
    name: gaussian
  regress_forces: false
  scale_file:  /home/jovyan/catlas/configs/ocp_config_checkpoints/scaling_factors/gemnet-dT.json

optim:
  batch_size: 32
  eval_batch_size: 32
  num_workers: 8
  lr_initial: 5.e-4
  optimizer: AdamW
  optimizer_params: {"amsgrad": True}
  # scheduler: ExponentialLR
  # gamma: 0.99
  scheduler: ReduceLROnPlateau
  mode: min
  factor: 0.8
  patience: 3
  max_epochs: 80
  ema_decay: 0.999
  clip_grad_norm: 10
  loss_energy: mae
  weight_decay: 0  # 2e-6 (TF weight decay) / 1e-4 (lr) = 2e-2