memory_cache_location: '/home/jovyan/shared-scratch/catlas/cache/'

input_options:
  bulk_file: 'catlas/bulk_structures/ocp_bulks_w_properties.db'
  adsorbate_file: 'catlas/adsorbate_structures/adsorbates.pkl'

output_options:
  pickle_final_output: False # True pickles the resulting predictions
  pickle_intermediate_outputs: True
  run_name: 'intermetallics_CO2RR_{{ GITHUB_RUN_ID }}'
  verbose: False

bulk_filters:
  filter_by_element_groups: ['transition metal']
  filter_by_object_size: 40 #60
  filter_by_pourbaix_stability: 
    max_decomposition_energy: 0
    lmdb_path: "catlas/pourbaix_diagrams/20220222_query.lmdb"
    V_lower: -1.35
    V_upper: -0.55
    V_step: 0.05
    pH_lower: 3
    pH_upper: 3
adsorbate_filters:
  filter_by_smiles: ['*H', '*CO','*OH','*CHO']

slab_filters:
  filter_by_object_size: 90
  filter_by_max_miller_index: 2

adslab_prediction_steps:
- gpu: true
  batch_size: 8
  label: 'dE_gemnet_is2re_finetuned'
  checkpoint_path: 'ocp_checkpoints/gemnet-is2re-finetuned-11-01.pt'

