memory_cache_location: '/home/jovyan/shared-scratch/catlas/cache_github'

input_options:
  bulk_file: 'catlas/bulk_structures/ocp_bulks_w_properties.db'
  adsorbate_file: 'catlas/adsorbate_structures/adsorbates.pkl'

output_options:
  pickle_final_output: True # True pickles the resulting predictions
  run_name: '{{ GITHUB_RUN_ID }}'
  verbose: False
  make_parity_plots: True

bulk_filters:
  filter_by_element_groups: ['transition_metal']
  filter_by_object_size: 40 # 60

adsorbate_filters:
  filter_by_smiles: ['*OH', '*O']

slab_filters:
  filter_by_object_size: 90
  filter_by_max_miller_index: 1 # Planar surfaces only like Pt111

adslab_prediction_steps:
- gpu: true
  batch_size: 4
  label: 'dE_gemnet_is2re_finetuned'
  checkpoint_path: 'ocp_checkpoints/gemnet-is2re-finetuned-11-01.pt'

