dask:
  partitions: -1 # Use automatic guess for number of partitions

memory_cache_location: '/home/jovyan/shared-scratch/catlas/cache_github'

output_options:
  pickle: True # True pickles the resulting predictions
  pickle_path: '/home/jovyan/shared-scratch/catlas/outputs/nitrides_CO2RR_{{ GITHUB_RUN_ID }}.pkl'
  cnofig_path: '/home/jovyan/shared-scratch/catlas/outputs/nitrides_CO2RR_{{ GITHUB_RUN_ID }}.yml'
  verbose: False

bulk_filters:
  filter_by_acceptable_elements: ['N', 'Sc', 'Ti', 'V', 'Cr', 'Mn', 'Fe', 'Co', 'Ni', 'Cu', 'Zn', 'Y', 'Zr', 'Nb', 'Mo', 'Tc', 'Ru', 'Rh', 'Pd', 'Ag', 'Cd', 'Ta', 'W', 'Re', 'Os', 'Ir', 'Pt', 'Au', 'Hg', 'Al', 'Ga', 'Sn', Pb', 'Bi', 'In']
  filter_by_object_size: 40 # 60
  filter_by_required_elements: ['N']

adsorbate_filters:
  filter_by_smiles: ['*H', '*CO','*OH','*CHO']

slab_filters:
  filter_by_object_size: 90
  filter_by_max_miller_index: 2

adslab_prediction_steps:
- step: predict
  type: direct
  gpu: true
  batch_size: 4
  label: 'dE_gemnet_is2re_finetuned'
  checkpoint_path: 'configs/ocp_config_checkpoints/gemnet-is2re-finetuned-11-01.pt'

