name: Automated screening

env:
  OMP_NUM_THREADS: '1'

on: [workflow_dispatch]

jobs:

  automated_screens:
    name: automated screens for various chemistries

    runs-on: [self-hosted, linux, shared-scratch]

    container:
      image: docker://ulissigroup/kubeflow:predictions
      volumes:
        - /home/jovyan/shared-scratch:/home/jovyan/shared-scratch

    timeout-minutes: 2880

    steps:
    - uses: azure/k8s-set-context@v2
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.ZULISSI_KUBECONFIG }}
        context: ulissigroup-desktops-fqdn
      id: setcontext
    - run: |
        mkdir -p /home/jovyan/shared-scratch/catlas_runners/$GITHUB_RUN_ID
        mkdir -p /home/jovyan/shared-scratch/catlas_runners/$GITHUB_RUN_ID/catlas
        ln -s /home/jovyan/shared-scratch/catlas_runners/$GITHUB_RUN_ID/catlas
        (cd /home/jovyan/ocp && git pull)
        rsync -a /home/jovyan/ocp /home/jovyan/shared-scratch/catlas_runners/$GITHUB_RUN_ID/
    - uses: actions/checkout@v3
      with:
        path: catlas
    - name: Test direct inference with kubecluster
      run: |
        cd catlas
        ln -s /home/jovyan/shared-scratch/catlas/ocp_checkpoints
        python setup.py develop
    - name: Startup dask cluster
      run: |
        sed -i "s/catlas-hybrid-cluster/catlas-hybrid-cluster-$GITHUB_RUN_ID/g" catlas/configs/dask_cluster/dask_operator/catlas-hybrid-cluster.yml
        sed -i "s/catlas-hybrid-cluster/catlas-hybrid-cluster-$GITHUB_RUN_ID/g" catlas/configs/dask_cluster/dask_operator/dask_connect.py
        kubectl apply -f catlas/configs/dask_cluster/dask_operator/catlas-hybrid-cluster.yml
        sleep 10
        kubectl scale --replicas=80 daskworkergroup catlas-hybrid-cluster-$GITHUB_RUN_ID-default-worker-group
        kubectl scale --replicas=0 daskworkergroup catlas-hybrid-cluster-$GITHUB_RUN_ID-gpu-worker-group
    - run: |
        cd catlas
        python bin/predictions.py configs/automated_screens/nitrides_CO2RR.yml configs/dask_cluster/dask_operator/dask_connect.py
    - run: |
        cd catlas
        python bin/predictions.py configs/automated_screens/intermetallics_ORR.yml configs/dask_cluster/dask_operator/dask_connect.py
    - run: |
        cd catlas
        python bin/predictions.py configs/automated_screens/intermetallics_HER.yml configs/dask_cluster/dask_operator/dask_connect.py
    - run: |
        cd catlas
        python bin/predictions.py configs/automated_screens/intermetallics_CO2RR.yml configs/dask_cluster/dask_operator/dask_connect.py
    - name: Shut down dask cluster
      if: always()
      run: |
        kubectl delete daskcluster catlas-hybrid-cluster-$GITHUB_RUN_ID
