name: deploy_jupyter_book

on:
  # Trigger the workflow on push to main branch
  workflow_dispatch:
  push:
    paths:
      - 'documentation/*'
      - '.github/workflows/deploy_jupyter_book.yml'

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  build_and_deploy_book:
    runs-on: ubuntu-latest

    container:
      image: docker://ulissigroup/catlas:latest

    steps:
    # Build the book
    - uses: actions/checkout@v3
    - name: Build the book
    - run: |
        pip install jupyter-book
        jupyter-book build documentation

    # Deploy the book's HTML to gh-pages branch
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: documentation/_build/html
