name: deploy_jupyter_book

on:
  # Trigger the workflow on push to main branch
  workflow_dispatch:
  push:
    paths:
      - 'documentation/*'
      - '.github/workflows/deploy_jupyter_book.yml'

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  test_local_scheduler:
    name: Test catlas with local scheduler

    runs-on: [self-hosted, linux]

    container:
      image: docker://ulissigroup/catlas:latest
      volumes:
        - /home/jovyan/shared-scratch:/home/jovyan/shared-scratch

    steps:
    # Build the book
    - name: Build the book
      run: |
        python setup.py develop
        pip install jupyter-book
        pip install markupsafe==2.0.0
        pip install pygments -U
        pip install sphinxcontrib-bibtex -U
        pip install -U Jinja2
        pip install sphinx_external_toc -U
        jupyter-book build documentation

    # Deploy the book's HTML to gh-pages branch
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: documentation/_build/html
