name: Test catlas with simple screening

env:
  OMP_NUM_THREADS: '1'

on: [push, workflow_dispatch]

jobs:
  test_local_scheduler:
    name: Test catlas with local scheduler

    runs-on: [self-hosted, linux]

    container:
      image: docker://ulissigroup/kubeflow:predictions
      volumes:
        - /home/jovyan/shared-scratch:/home/jovyan/shared-scratch

    steps:
    - name: Run example predictions
      uses: actions/checkout@v2
    - run: |
        (cd /home/jovyan/ocp && git pull) 
        ln -s /home/jovyan/shared-scratch/catlas/ocp_checkpoints
        ln -s /home/jovyan/shared-scratch/catlas/npz-files ./catlas/parity/
        ln -s /home/jovyan/shared-scratch/catlas/pourbaix_diagrams ./catlas/
        python setup.py develop
        python bin/predictions.py configs/tests/test_metals.yml configs/dask_cluster/local_cluster/local_cluster.py
  test_local_scheduler_relaxation:
    name: Test catlas with local scheduler and cpu relaxations

    runs-on: [self-hosted, linux]

    container:
      image: docker://ulissigroup/kubeflow:predictions
      volumes:
        - /home/jovyan/shared-scratch:/home/jovyan/shared-scratch

    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
    - name: Run cpu relaxations test
      run: |
        (cd /home/jovyan/ocp && git pull) 
        ln -s /home/jovyan/shared-scratch/catlas/ocp_checkpoints
        ln -s /home/jovyan/shared-scratch/catlas/npz-files ./catlas/parity/
        ln -s /home/jovyan/shared-scratch/catlas/pourbaix_diagrams ./catlas/
        python setup.py develop
        python bin/predictions.py configs/tests/test_cpu_relax.yml configs/dask_cluster/local_cluster/local_cluster.py
      env:
        OMP_NUM_THREADS: 4

  test_kubecluster:
    name: Test catlas with kubecluster

    runs-on: [self-hosted, linux, shared-scratch]

    container:
      image: docker://ulissigroup/kubeflow:predictions
      volumes:
        - /home/jovyan/shared-scratch:/home/jovyan/shared-scratch
    steps:
    - uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.ZULISSI_KUBECONFIG }}
        context: ulissigroup-desktops-fqdn
      id: setcontext
    - run: |
        mkdir -p /home/jovyan/shared-scratch/catlas_runners/$GITHUB_RUN_ID
        mkdir -p /home/jovyan/shared-scratch/catlas_runners/$GITHUB_RUN_ID/catlas
        ln -s /home/jovyan/shared-scratch/catlas_runners/$GITHUB_RUN_ID/catlas
        (cd /home/jovyan/ocp && git pull)
        rsync -a /home/jovyan/ocp /home/jovyan/shared-scratch/catlas_runners/$GITHUB_RUN_ID/
    - uses: actions/checkout@v2
      with:
        path: catlas
    - name: Test direct inference with kubecluster
      run: |
        cd catlas
        ln -s /home/jovyan/shared-scratch/catlas/ocp_checkpoints
        python setup.py develop
    - name: Startup dask cluster
      run: |
        sed -i "s/catlas-hybrid-cluster/catlas-hybrid-cluster-$GITHUB_RUN_ID/g" catlas/configs/dask_cluster/dask_operator/catlas-hybrid-cluster.yml
        sed -i "s/catlas-hybrid-cluster/catlas-hybrid-cluster-$GITHUB_RUN_ID/g" catlas/configs/dask_cluster/dask_operator/dask_connect.py
        kubectl apply -f catlas/configs/dask_cluster/dask_operator/catlas-hybrid-cluster.yml
        sleep 10
        kubectl scale --replicas=2 daskworkergroup catlas-hybrid-cluster-$GITHUB_RUN_ID-default-worker-group
    - name: Test cpu relaxation inference with kubecluster
      run: |
        cd catlas
        python bin/predictions.py configs/tests/test_cpu_relax.yml configs/dask_cluster/dask_operator/dask_connect.py
    - name: Test gpu relaxation with kubecluster
      run: |
        cd catlas
        kubectl scale --replicas=1 daskworkergroup catlas-hybrid-cluster-$GITHUB_RUN_ID-gpu-worker-group
        python bin/predictions.py configs/tests/test_gpu_relax.yml configs/dask_cluster/dask_operator/dask_connect.py
    - name: Shut down dask cluster
      if: always()
      run: |
        kubectl delete daskcluster catlas-hybrid-cluster-$GITHUB_RUN_ID
