name: Test catlas with simple screening

env:
  OMP_NUM_THREADS: '1'

on: [push]

jobs:
  test_local_scheduler:
    name: Test catlas with local scheduler

    runs-on: [self-hosted, linux]

    container:
      image: docker://ulissigroup/kubeflow:predictions

    steps:
    - run: |
        sudo apt update && sudo apt install git-lfs
    - name: Run example predictions
      uses: actions/checkout@v2
      with: 
        lfs: true
    - run: |
        (cd /home/jovyan/ocp && git pull && git checkout ocpcalc_fix) 
        python setup.py develop
        python bin/predictions.py configs/tests/test_local_scheduler.yml

  test_kubecluster:
    name: Test catlas with kubecluster

    runs-on: [self-hosted, linux, shared-scratch]

    container:
      image: docker://ulissigroup/kubeflow:predictions
      volumes:
        - /home/jovyan/shared-scratch:/home/jovyan/shared-scratch

    steps:
    - uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.ZULISSI_KUBECONFIG }}
        context: ulissigroup-desktops-fqdn
      id: setcontext
    - run: |
        sudo apt update && sudo apt install git-lfs
        mkdir -p /home/jovyan/shared-scratch/catlas_runners/$GITHUB_RUN_ID
        mkdir -p /home/jovyan/shared-scratch/catlas_runners/$GITHUB_RUN_ID/catlas
        ln -s /home/jovyan/shared-scratch/catlas_runners/$GITHUB_RUN_ID/catlas
        (cd /home/jovyan/ocp && git pull && git checkout ocpcalc_fix)
        rsync -a /home/jovyan/ocp /home/jovyan/shared-scratch/catlas_runners/$GITHUB_RUN_ID/
    - uses: actions/checkout@v2
      with:
        lfs: true
        path: catlas
    - run: |
        cd catlas
        python setup.py develop
        python bin/predictions.py configs/tests/test_kubecluster.yml

